# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 08:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('abstract', models.TextField()),
                ('keywords', models.CharField(max_length=512)),
                ('pdf', models.FileField(upload_to='articles')),
                ('submittedOn', models.DateField(default=datetime.date(2017, 6, 15))),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('issue', models.IntegerField(blank=True, null=True)),
                ('publishedOn', models.DateField(blank=True, null=True)),
                ('isPublished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='LikeArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'likeCategories',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnum', models.CharField(blank=True, max_length=12)),
                ('isOutsider', models.BooleanField(default=False)),
                ('profession', models.CharField(blank=True, choices=[('ST', 'Student'), ('AL', 'Alumnus/alumna'), ('LC', 'Lecturer'), ('LS', 'Library Staff'), ('AS', 'Administrative Staff'), ('MS', 'Management Staff'), ('OT', 'Other')], max_length=30)),
                ('ugorpg', models.CharField(blank=True, choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate')], max_length=2)),
                ('dept', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('CS', 'Computer Science'), ('ECE', 'Electronics and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('IT', 'Information Technology'), ('EIE', 'Electronics and Instrumentation Engineering'), ('MECH', 'Mechanical Engineering'), ('CIV', 'Civil Engineering'), ('VLSI', 'VLSI Design'), ('ES', 'Embedded Systems'), ('EPE', 'Electrical Power Engineering'), ('WMC', 'Wireless and Mobile Communication')], max_length=4)),
                ('exactprofession', models.CharField(blank=True, max_length=30)),
                ('place', models.CharField(blank=True, max_length=40)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
