# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-15 09:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170615_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='re_password',
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
